<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9115" started-at="2024-06-29T04:13:07Z" finished-at="2024-06-29T04:13:16Z">
    <groups>
      <group name="smoke">
        <method signature="FaceBook.CreatenewAccount()[pri:2, instance:org.faild.FaceBook@5622fdf]" name="CreatenewAccount" class="org.faild.FaceBook"/>
        <method signature="FaceBook.tsetLogin()[pri:1, instance:org.faild.FaceBook@5622fdf]" name="tsetLogin" class="org.faild.FaceBook"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="FaceBook.tsetLogin()[pri:1, instance:org.faild.FaceBook@5622fdf]" name="tsetLogin" class="org.faild.FaceBook"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Default test" duration-ms="9115" started-at="2024-06-29T04:13:07Z" finished-at="2024-06-29T04:13:16Z">
      <class name="org.faild.FaceBook">
        <test-method status="PASS" signature="browserOpen()[pri:0, instance:org.faild.FaceBook@5622fdf]" name="browserOpen" is-config="true" duration-ms="1926" started-at="2024-06-29T04:13:07Z" finished-at="2024-06-29T04:13:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpen -->
        <test-method status="PASS" signature="LauncTime()[pri:0, instance:org.faild.FaceBook@5622fdf]" name="LauncTime" is-config="true" duration-ms="1" started-at="2024-06-29T04:13:09Z" finished-at="2024-06-29T04:13:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LauncTime -->
        <test-method status="FAIL" signature="tsetLogin()[pri:1, instance:org.faild.FaceBook@5622fdf]" name="tsetLogin" duration-ms="1132" started-at="2024-06-29T04:13:09Z" finished-at="2024-06-29T04:13:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[faile assert expected [vishnunath] but found [vishnunat]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: faile assert expected [vishnunath] but found [vishnunat]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.faild.FaceBook.tsetLogin(FaceBook.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tsetLogin -->
        <test-method status="PASS" signature="browserClosingTime()[pri:0, instance:org.faild.FaceBook@5622fdf]" name="browserClosingTime" is-config="true" duration-ms="8" started-at="2024-06-29T04:13:10Z" finished-at="2024-06-29T04:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserClosingTime -->
        <test-method status="PASS" signature="CreatenewAccount()[pri:2, instance:org.faild.FaceBook@5622fdf]" name="CreatenewAccount" duration-ms="6023" started-at="2024-06-29T04:13:10Z" finished-at="2024-06-29T04:13:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatenewAccount -->
        <test-method status="PASS" signature="LauncTime()[pri:0, instance:org.faild.FaceBook@5622fdf]" name="LauncTime" is-config="true" duration-ms="0" started-at="2024-06-29T04:13:10Z" finished-at="2024-06-29T04:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LauncTime -->
        <test-method status="PASS" signature="ccloseBrowser()[pri:0, instance:org.faild.FaceBook@5622fdf]" name="ccloseBrowser" is-config="true" duration-ms="0" started-at="2024-06-29T04:13:16Z" finished-at="2024-06-29T04:13:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ccloseBrowser -->
        <test-method status="PASS" signature="browserClosingTime()[pri:0, instance:org.faild.FaceBook@5622fdf]" name="browserClosingTime" is-config="true" duration-ms="0" started-at="2024-06-29T04:13:16Z" finished-at="2024-06-29T04:13:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserClosingTime -->
      </class> <!-- org.faild.FaceBook -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
