<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="V_Varsha2023" name="org.facebook.FaceBook2" tests="2" failures="1" timestamp="28 Jun 2024 08:57:01 GMT" time="14.746" errors="0">
  <testcase name="tsetLogin" time="6.296" classname="org.facebook.FaceBook2">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	assertfail expected [vishnunathvishnunathvishnunath] but found [vishnunath],
	verify the url expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
assertfail expected [vishnunathvishnunathvishnunath] but found [vishnunath],
verify the url expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.facebook.FaceBook2.tsetLogin(FaceBook2.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- tsetLogin -->
  <testcase name="CreatenewAccount" time="8.450" classname="org.facebook.FaceBook2"/>
</testsuite> <!-- org.facebook.FaceBook2 -->
